class CustomJsonSettings:
    TEMPLATE_NAME = "template_name"
    TEXT = "text"
    DEFAULT = "default"
    DF_CAN_BE_CHANGED = "default_can_be_changed"
    ATTRS = "attrs"
    TYPE = "type"
    CAN_BE_ADDED_ATTRIBUTES = "can_be_added_attributes"
    DONT_SHOWN = "dont_shown"
    STR = "str"
    INT = "int"
    BOOL = "bool"
    DICT = "dict"
    LIST = "list"
